Repository ita-social-projects/dokazovi-fe, pull requests merged in 2021-08, with the labels that each got.

#481 Fix origins, post types label names order, correct the post type label name at the Materials page
  src/old/modules/materials/components/MaterialsView.tsx
Labels: Materials Page, bug, frontend

#495 Bugfix #142 The author's profile page cannot be opened in a new browser tab using the right-clicking
  src/old/lib/components/Experts/ExpertDataCard.tsx
  src/old/lib/components/Experts/ExpertPhotoDataCard.tsx
Labels: bug, frontend

#493 #489 / remove text fields from carousel & link with post
  src/components/Posts/Cards/ImportantPostPreviewCard/ImportantPostPreviewCard.spec.tsx
  src/components/Posts/Cards/ImportantPostPreviewCard/ImportantPostPreviewCard.styles.ts
  src/components/Posts/Cards/ImportantPostPreviewCard/ImportantPostPreviewCard.tsx
Labels: frontend

#490 Bugfix #155 redirecting in material's card
  src/components/Posts/PostInfo/PostInfo.styles.ts
  src/components/Posts/PostInfo/PostInfo.tsx
Labels: bug, frontend

#499 bugFix # 156 create error message
  src/locales/uk/parts/common.ts
  src/old/lib/components/Experts/ExpertsList.tsx
  src/old/lib/components/Posts/PostsList.tsx
Labels: bug, frontend

#501 bug fix #145 No Authors cards are displayed on the 'Автори' page when all checkboxes are unmarked
  src/models/experts/asyncActions.ts
Labels: bug, frontend

#500 fix bug with items size and accord. arrow color
  src/models/utilities/filterConfigTypes.ts
  src/views/Profile/MaterialsView/FilterSection.tsx
  src/views/Profile/MaterialsView/MaterialsDraft.tsx
  src/views/Profile/MaterialsView/MaterialsPublished.tsx
  src/views/Profile/MaterialsView/PostsList.tsx
  src/views/Profile/MaterialsView/styles/FilterSection.styles.ts
  src/views/Profile/MaterialsView/styles/PostsList.styles.ts
Labels: bug

#506 Fixed counter & posts loading in Materials page
  src/old/modules/materials/components/MaterialsView.tsx
Labels: bug

#504 Fixed filters in Material's page when all of them empty
  src/old/modules/materials/components/MaterialsView.tsx
Labels: bug

#502 Fix items width acc to diff breakpoints at the Materials tab
  src/views/Profile/MaterialsView/PostsList.tsx
  src/views/Profile/MaterialsView/styles/PostsList.styles.ts
Labels: bug

#516 Sorted filter checkboxes in alphabet order in materials page
  src/old/lib/utilities/sorting.ts
  src/old/modules/materials/components/MaterialsView.tsx
Labels: bug, frontend

#515 bugFix#171 changed link on TranslationPostPreviewCard.tsx
  src/components/Posts/Cards/TranslationPostPreviewCard/TranslationPostPreviewCard.tsx
Labels: bug, frontend

#522 BugFix #158 wrong margin top above filter block
  src/old/lib/components/Filters/CheckboxLeftsideFilterForm.styles.ts
Labels: bug, frontend

#520 Change empty output message position
  src/components/Notifications/Notification.tsx
  src/old/modules/experts/components/ExpertMaterialsContainer.tsx
Labels: bug, frontend

#526 Add correct redirection to author page
  src/components/Posts/Cards/TranslationPostPreviewCard/TranslationPostPreviewCard.tsx
Labels: bug, frontend

#530 Add redirect button at empty result
  src/components/Notifications/Notification.styles.ts
  src/components/Notifications/Notification.tsx
  src/locales/uk/parts/common.ts
Labels: bug, frontend

#533 Add new favicon
  public/favicon.ico
Labels: frontend
