Repository ita-social-projects/dokazovi-fe, pull requests merged in 2021-07, with the labels that each got.

#436 Issue#434 add the possibility to change the preview image during the post updating
  src/old/lib/components/Editor/Blots/FigureBlot.ts
  src/old/lib/components/Editor/CustomModules/BackgroundImageContainer/BackgroundImageContainer.tsx
  src/old/lib/components/Editor/CustomModules/BackgroundImageContainer/backgroundImageContainer.style.ts
  src/old/lib/components/Editor/CustomModules/ImageFromFileHandler.ts
  src/old/lib/components/Editor/CustomModules/ImageFromURLHandler.ts
  src/old/lib/components/Editor/CustomModules/ImageHandlersContainer.tsx
  src/old/lib/components/Editor/CustomModules/UrlInputModal.tsx
  src/old/lib/components/Editor/CustomModules/VideoUrlInputModal.tsx
  src/old/lib/components/Editor/CustomModules/types.ts
  src/old/lib/components/Editor/Editors/ArticleEditorToolbar.tsx
  src/old/lib/components/Editor/Editors/NoteEditorToolbar.tsx
  src/old/lib/components/Editor/Editors/TextPostEditor.tsx
  src/old/lib/components/Editor/Editors/VideoEditor.tsx
  src/old/lib/components/Editor/Editors/VideoEditorToolbar.tsx
  src/old/lib/components/Editor/GeneralEditor.tsx
  src/old/lib/components/Editor/PreviewInput.tsx
  src/old/lib/components/Editor/generalEditor.styles.css
  src/old/lib/components/Editor/icons.ts
  src/old/lib/components/Editor/types.ts
  src/old/lib/components/Editor/utilities.ts
  src/old/modules/postCreation/components/ArticleCreation.tsx
  src/old/modules/postCreation/components/NoteCreation.tsx
  src/old/modules/postCreation/components/PostAuthorSelection/PostAuthorSelection.spec.tsx
  src/old/modules/postCreation/components/PostAuthorSelection/PostAuthorSelection.tsx
  src/old/modules/postCreation/components/PostCreationButtons.tsx
  src/old/modules/postCreation/components/PostDirectionsSelector.tsx
  src/old/modules/postCreation/components/PostOriginsSelector.tsx
  src/old/modules/postCreation/components/TextPostCreation.tsx
  src/old/modules/postCreation/components/VideoCreation.tsx
  src/old/modules/postUpdation/components/ArticleUpdation.tsx
  src/old/modules/postUpdation/components/NoteUpdation.tsx
  src/old/modules/postUpdation/components/PostUpdationWrapper.tsx
  src/old/modules/postUpdation/components/TextPostUpdation.tsx
  src/old/modules/postUpdation/components/VideoUpdation.tsx
  src/views/postCreation/TextPostCreation.tsx
  src/views/postCreation/VideoCreation/VideoCreation.tsx
  src/views/postCreation/VideoCreation/VideoPostCreation.tsx
  src/views/postUpdation/TextPostUpdation.tsx
  src/views/postUpdation/VideoUpdation/VideoPostUpdation.tsx
  src/views/postUpdation/VideoUpdation/VideoUpdation.tsx
Labels: frontend

#433 Create admin page
  src/App.tsx
  src/components/Posts/Cards/ImportantPostPreviewCard/ImportantPostPreviewCard.styles.ts
  src/components/Posts/Cards/ImportantPostPreviewCard/ImportantPostPreviewCard.tsx
  src/components/Posts/Cards/types.ts
  src/models/main/reducers.ts
  src/old/lib/components/Footer/Footer.styles.ts
  src/old/lib/components/Footer/Footer.tsx
  src/old/lib/components/Header/AccountMenu.tsx
  src/old/lib/components/Users/AdminPage/components/AddImportantMaterial.tsx
  src/old/lib/components/Users/AdminPage/components/AdminPageWrapper.tsx
  src/old/lib/components/Users/AdminPage/components/FilterSection.tsx
  src/old/lib/components/Users/AdminPage/components/ImportantView.tsx
  src/old/lib/components/Users/AdminPage/components/MaterialFilter.tsx
  src/old/lib/components/Users/AdminPage/components/OperationView.tsx
  src/old/lib/components/Users/AdminPage/components/PostPreviewWrapper.tsx
  src/old/lib/components/Users/AdminPage/components/Sidemenu.tsx
  src/old/lib/components/Users/AdminPage/styles/FilterSection.styles.ts
  src/old/lib/components/Users/AdminPage/styles/ImportantView.styles.ts
  src/old/lib/components/Users/AdminPage/styles/OperationView.styles.ts
  src/old/lib/components/Users/AdminPage/styles/PostPreviewWrapper.styles.ts
  src/old/lib/components/Users/AdminPage/styles/Sidemenu.styles.ts
  src/old/lib/types.ts
  src/old/modules/main/components/ImportantContainer.tsx
  src/old/navigation/Router.tsx
  src/old/navigation/router-config.ts
  src/old/navigation/types.ts
Labels: frontend

#442 Issue 366 and 441 Implement breadcrumbs for posts
  src/App.tsx
  src/components/Breadcrumbs/Basic/BasicBreadcrumbs.styles.ts
  src/components/Breadcrumbs/Basic/BasicBreadcrumbs.tsx
  src/components/Breadcrumbs/Basic/BreadcrumbsProvider.tsx
  src/components/Breadcrumbs/Basic/breadcrumbs-config.ts
  src/components/Breadcrumbs/PostBreadcrumbs.tsx
  src/components/Breadcrumbs/index.ts
  src/old/modules/posts/components/PostView.tsx
  src/old/modules/posts/styles/PostView.styles.ts
  src/old/navigation/Router.tsx
Labels: PostView Page, enhancement, frontend

#445 Fix eslint warnings
  src/components/ConditionNav/ConditionNav.styles.ts
  src/components/Editor/CustomModules/ImageFromFileHandler.ts
  src/components/Editor/utilities.ts
  src/models/properties/reducers.ts
  src/old/lib/components/Service/Oath2Redirect.tsx
  src/old/modules/posts/components/PostViewWrapper.tsx
  src/views/Conditions/Conditions.styles.ts
  src/views/Conditions/Conditions.tsx
  src/views/postCreation/TextPostCreation.tsx
  src/views/postCreation/VideoCreation/VideoPostCreation.tsx
Labels: frontend

#450 Issue #438 cover with tests all components in src/components/Chips directory
  src/components/Chips/ChipsList/ChipsList.spec.tsx
  src/components/Chips/PostDirectionChip/PostDirectionChip.spec.tsx
  src/components/Chips/PostDirectionChip/PostDirectionChip.tsx
Labels: frontend

#455 Change filter section title
  src/old/modules/experts/components/ExpertsView.tsx
Labels: frontend

#457 Issue 456 improve post breadcrumbs component
  src/components/Breadcrumbs/PostBreadcrumbs.tsx
  src/old/modules/posts/components/PostView.tsx
Labels: frontend

#463 Issue 461 сreate user profile page
  src/App.tsx
  src/components/Header/AccountMenu.styles.ts
  src/components/Header/AccountMenu.tsx
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/Header/PostCreationMenu.tsx
  src/locales/uk/parts/common.ts
  src/old/lib/components/Footer/Footer.styles.ts
  src/old/lib/components/Footer/Footer.tsx
  src/old/lib/types.ts
  src/old/navigation/router-config.ts
  src/views/Profile/MaterialsView.tsx
  src/views/Profile/OperationView.tsx
  src/views/Profile/Profile.tsx
  src/views/Profile/Sidemenu.tsx
  src/views/Profile/styles/MaterialsView.styles.ts
  src/views/Profile/styles/OperationView.styles.ts
  src/views/Profile/styles/Sidemenu.styles.ts
Labels: frontend

#467 Issue 462 add change and reset password feature
  package.json
  src/components/Form/Buttons/BasicButton.tsx
  src/components/Form/Buttons/index.ts
  src/components/Form/Buttons/styles/BasicButton.style.tsx
  src/components/Form/Inputs/BasicInput.tsx
  src/components/Form/Inputs/index.ts
  src/components/Form/Inputs/styles/BasicInput.style.tsx
  src/components/Form/index.ts
  src/locales/uk/parts/common.ts
  src/locales/uk/parts/loginRegistration.ts
  src/locales/uk/parts/passwordForms.ts
  src/locales/uk/ukrainian.ts
  src/old/lib/components/Users/LoginModal.styles.ts
  src/old/lib/components/Users/LoginModal.tsx
  src/old/lib/components/Users/validationRules.ts
  src/old/lib/utilities/API/api.ts
  src/old/navigation/router-config.ts
  src/views/PasswordReset/PasswordResetView.style.tsx
  src/views/PasswordReset/PasswordResetView.tsx
  src/views/PasswordUpdate/PasswordUpdateView.style.tsx
  src/views/PasswordUpdate/PasswordUpdateView.tsx
  src/views/Profile/OperationView.tsx
  src/views/Profile/PasswordChangeView.tsx
  src/views/Profile/styles/PasswordChangeView.styles.ts
  yarn.lock
Labels: frontend

#472 Issue 459 add materials tab at the profile
  src/components/Notifications/Notification.tsx
  src/locales/uk/parts/common.ts
  src/models/expertMaterialsDraft/asyncActions.ts
  src/models/expertMaterialsDraft/index.ts
  src/models/expertMaterialsDraft/reducers.ts
  src/models/expertMaterialsDraft/selectors.ts
  src/models/expertMaterialsPublished/asyncActions.ts
  src/models/expertMaterialsPublished/index.ts
  src/models/expertMaterialsPublished/reducers.ts
  src/models/expertMaterialsPublished/selectors.ts
  src/models/expertMaterialsPublished/types.ts
  src/models/materials/types.ts
  src/models/rootReducer.ts
  src/models/utilities/filterConfigTypes.ts
  src/old/lib/components/Filters/CheckboxLeftsideFilterForm.styles.ts
  src/old/lib/components/LoadMoreButton/LoadMoreButton.tsx
  src/old/lib/components/Modals/ConfirmationModalWithButton.tsx
  src/old/lib/constants/posts.ts
  src/old/lib/types.ts
  src/old/lib/utilities/API/api.ts
  src/old/lib/utilities/API/types.ts
  src/views/Profile/MaterialsView.tsx
  src/views/Profile/MaterialsView/ExpertMaterialsViewWrapper.tsx
  src/views/Profile/MaterialsView/FilterSection.tsx
  src/views/Profile/MaterialsView/MaterialsDraft.tsx
  src/views/Profile/MaterialsView/MaterialsPublished.tsx
  src/views/Profile/MaterialsView/MaterialsView.tsx
  src/views/Profile/MaterialsView/PostsList.tsx
  src/views/Profile/MaterialsView/styles/MaterialsByStatus.styles.ts
  src/views/Profile/MaterialsView/styles/PostsList.styles.ts
  src/views/Profile/OperationView.tsx
  src/views/Profile/styles/MaterialsView.styles.ts
  src/views/Profile/styles/OperationView.styles.ts
  src/views/Profile/styles/Sidemenu.styles.ts
Labels: frontend

#475 Slider page limit fix
  src/models/main/asyncActions.ts
  src/old/lib/constants/posts.ts
Labels: frontend

#479 Fix bug with posts by important image sorting at the admin page
  src/models/materialsImportant/asyncActions.ts
  src/models/materialsImportant/index.ts
  src/models/materialsImportant/reducers.ts
  src/models/materialsImportant/selectors.ts
  src/models/rootReducer.ts
  src/old/lib/components/Users/AdminPage/components/AddImportantMaterial.tsx
  src/old/lib/components/Users/AdminPage/components/FilterSection.tsx
Labels: bug, frontend
